[build-system]
requires = ["setuptools>=42", "wheel", "ninja"]
build-backend = "setuptools.build_meta"

# Not necessary for packaging but every self-respecting Python
# package should a) use black and b) fix the WRONG default.
[tool.black]
line-length = 79

[tool.cibuildwheel]
test-requires = "imageio"
test-command = "python -m unittest discover {project}/tests test_*.py"
