[build-system]
requires = ["setuptools>=42", "wheel", "ninja"]
build-backend = "setuptools.build_meta"

# Not necessary for packaging but every self-respecting Python
# package should a) use black and b) fix the WRONG default.
[tool.black]
line-length = 79

[tool.cibuildwheel]
build = ["cp38-manylinux_x86_64", "pp38-manylinux_x86_64"]
test-requires = ""
test-command = "python -m unittest discover {project}/tests test_*.py"

 # Setuptools bug causes collision between pypy and cpython artifacts
 # (from pybind/cmake_example, is necessary)
before-build = "rm -rf {project}/build"
