name: Build Python Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_TEST_REQUIRES: imageio
          CIBW_TEST_COMMAND: "python -m unittest discover tests test_*.py"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
