# This is a basic workflow to help you get started with Actions

name: Generate All Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [addtree_continued]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install gurobipy
          pip install -U scikit-learn

      - name: Install veritas
        run: |
          git submodule init && git submodule update
          pip install .

      - name: Generate python_examples
        run: python docs/generate_python_examples.py

      - name: Generate all docs without pybinds
        run: cd docs && make html
